### ISSUE TITLE
Potential issues and questions

### ISSUE THREAD

**Issue by FlayaN** [Starfield-Reverse-Engineering/Starfield-RE-vcpkg#2]
Hello! I was looking over the current implementation of the automatic vcpk port update and I found some potiential issues that I wasn't sure about, also some questions:

1. Should we also update `.github/update-registry.ps1` when "updating docs..." is run (We're already fetching the latest VCPKG sha there)? Otherwise this might need to be manually updated

```yml
env:
  VCPKG_COMMIT_ID: 095ee8757ec933b22d445738d2dbb1ce89bb8021
```

2. Should we allow multiple runs on the same days due to using version-date? AKA there can be multiple versions with the same versions out there. Currently it creates multiple commits with the same title with different ref, shas and git-tree

Below are example of this (Done on a fork of this branch):
![image](https://github.com/Starfield-Reverse-Engineering/Starfield-RE-vcpkg/assets/964655/0eca09ec-ced2-4cf2-9de0-61f562314157)
![image](https://github.com/Starfield-Reverse-Engineering/Starfield-RE-vcpkg/assets/964655/42cc8ff2-9d9f-4bec-8eaa-8ce8598e1228)

This can be fixed by either fail the second run or add a incremental build number to the end of the date like specified [here](https://learn.microsoft.com/en-us/vcpkg/users/versioning#version-date)

3. Currently it fails if running `Starfield-RE-vcpkg/.github/workflows/update_registry.yml` workflow twice in row (Can only happen if the upstream is not changed between runs). Should this be fixed? Fail nicer? :P

4. Can't we amend the "build: update registry" commit into "port: DATE"? Nicer history
This was also mentioned as step 11 here:
_Originally posted by @ThirdEyeSqueegee in https://github.com/Starfield-Reverse-Engineering/CommonLibSF/issues/13#issuecomment-1710919327_

**Comment by gottyduke** [comment]
Hello FlayaN!

> Should we also update .github/update-registry.ps1 when "updating docs..." is

I think you mean `update_registry.yml`, but yes that could be also updated.

> Should we allow multiple runs on the same days due to using version-date?

The current script will change the existing entry to point to the new sha, git-tree and commit (a.k.a. multiple runs in the same day), so it's kinda overwriting the old entry if that happens. I admit it's not granular enough, if that becomes an issue(e.g. if we need to keep every version in the history instead of overwriting), this could be fixed by appending incremental minor versions.

> Currently it fails if running Starfield-RE-vcpkg/.github/workflows/update_registry.yml workflow twice in row (Can only happen if the upstream is not changed between runs).

That'd be an oversight, I actually didn't test with the same REF twice, also do you think it's obligatory to pass the upstream's sha to the action, so it only operate based on that exact commit? Currently script can handle a sha passed in, but I didn't know if we needed it so I also made the script to fill the sha with the latest commit fetched from upstream.

> Can't we amend the "build: update registry" commit into "port: DATE"?

That would be a squash, I expect that's what you mean? However, it's not doable with current workflow(not github _workflow_), the 2nd `build: update registry` is updating the docs, and it needs a commit sha pointing to this vcpkg repo that has the latest `port/*` `versions/baseline.json` `versions/c-` changes, in this case, the `port: version-date` commit. Can't squash them because then the sha in the readme will be invalid, it no longer points to the `port: version-date` commit, because that has been squashed. The --amend process is already done inside the script, if you are refereing to the step that parses the git-tree of ports/ folder

**Comment by gottyduke** [comment]
Regarding the last question: however it's worth noting that we need to move the `version/c-/commonlibsf.json` file change into the `port: version-date` commit, it's weird to have it pushed with docs update. That's an oversight from me.

**Comment by FlayaN** [comment]
>Regarding the last question: however it's worth noting that we need to move the version/c-/commonlibsf.json file change into the port: version-date commit, it's weird to have it pushed with docs update. That's an oversight from me.

If you move the `version/c-/commonlibsf.json` into the port commit, then the second commit can maybe be renamed to `docs: update registry`

>That'd be an oversight, I actually didn't test with the same REF twice, also do you think it's obligatory to pass the upstream's sha to the action, so it only operate based on that exact commit? Currently script can handle a sha passed in, but I didn't know if we needed it so I also made the script to fill the sha with the latest commit fetched from upstream.

Yeah I saw that initially it had the sha passed from the upstream's sha, not sure why that was removed and instead changed to fetch latest sha.

I guess a simple check would be to compare the latest SHA in portfile with the incoming sha.

>I think you mean update_registry.yml, but yes that could be also updated.

Yeah sorry! Yeah meant that, not sure if that's a big thing though


Thanks for answering, nice flow!
Btw unrelated, can't a licence for this repo. Was a bit curious about building a proper reusable github action around this. Is this something I can base on these scripts? With credit ofc

**Comment by gottyduke** [comment]
Feel free to use the script, after the issues are addressed ofc 😃
