### ISSUE TITLE
vcpkg fails for the latest port (2023-09-09.1)

### ISSUE THREAD

**Issue by ThirdEyeSqueegee** [Starfield-Reverse-Engineering/Starfield-RE-vcpkg#6]
Maybe it doesn't like the the `.1`?
```cmake
1> [CMake] error: Failed to load port because versions are inconsistent. The file "AppData\Local\vcpkg\registries\git-trees\1a92e75527b8732d084970e6a64f4620ce062a42" contains the version commonlibsf@2023-09-09, but the version database indicates that it should be commonlibsf@2023-09-09.1.
```

**Comment by gottyduke** [comment]
It was intentional for distinguish version collisions ( #2 ), this was tested by me and FlayaN. However it requires main repo also updates the ci script to accomodate the changes here, and at that time I had a PR on main branch, so I didn't push the local commits yet. Will do it tomorrow first chance I get.
